playtron-os/rpm-specs-gaming

- .github/workflows/gamingos-scripts.yml
- gamingos-scripts/gamingos-scripts.spec
This is a custom built RPM spec file.
> [gamingos-scripts] Add gamingos-scripts

- .github/workflows/gamescope-session-upload.yml
- .github/workflows/gamescope-session.yml
- .github/workflows/kernel-upload.yml
- .github/workflows/kernel.yml
- .github/workflows/mesa-upload.yml
- .github/workflows/mesa.yml
- .github/workflows/playtron-os-scripts-upload.yml
- .github/workflows/playtron-os-scripts.yml
- kernel.sh
This builds Linux 6.3.13 which is the last release of Linux 6.3.
GitHub Actions workflows have been added for the Linux kernel.
Resolves #2
> [kernel] Build a Fedora kernel (take 2)

- .github/workflows/python3-edl-upload.yml
- .github/workflows/python3-edl.yml
- python3-edl/python3-edl.spec
for the Emergency Download client for managing Qualcomm Arm SoCs.
> [python3-edl] Add new RPM spec

- .github/workflows/python3-edl-upload.yml
EDL does not support 32-bit builds.
> [python3-edl] Build 64-bit only

- .github/workflows/reaper-upload.yml
- .github/workflows/reaper.yml
- reaper/reaper.spec
Packaging our customized `reaper` command-line tool.
Sibling PR adding this package as a dependency to playserve: https://bitbucket.org/playtron-one/playserve/pull-requests/275
> add reaper package

- .github/workflows/valve-firmware-upload.yml
- .github/workflows/valve-firmware.yml
- valve-firmware/valve-firmware.spec
This includes firmware files for the Steam Deck OLED.
> Add valve-firmware package

- playtron-os-files/playtron-os-files.spec
Packaging updates!
- deleted files
- added files
> fix playtron-os-files packaging issues

- mesa/Mesa-MLAA-License-Clarification-Email.txt
this was accidently deleted with the update to Mesa 24.1.2.
> [mesa] Add missing source file

- gamescope-session/gamescope-session.spec
- playtron-os-files/playtron-os-files.spec
- update gamescope-session (power button fix)
- updates playtron-os-files (drive formatting fix)
> OS-75 Updates

- playtron-os-files/playtron-os-files.spec
Also include the new NetworkManager configuration file.
> update playtron-os-files to 0.16.8

- gamescope-session-playtron/gamescope-session-playtron.spec
- playtron-os-files/playtron-os-files.spec
update the following packages:
- gamescope-session-playtron
- playtron-os-files
> update gamescope-session-playtron and playtron-os-files

- playtron-os-files/playtron-os-files.spec
> [playtron-os-files] Update to 0.16.11

- gamescope-session-playtron/gamescope-session-playtron.spec
> [gamescope-session-playtron] Update to 0.2.4

- playtron-os-files/playtron-os-files.spec
> [playtron-os-files] Update to 0.17.0

- gamescope-session-playtron/gamescope-session-playtron.spec
- gamescope-session/gamescope-session.spec
- playtron-os-files/playtron-os-files.spec
Tested by locally building each updated package.
> OS-117 package updates for switch to sddm and slow media boot fix

- gamescope-session/gamescope-session.spec
The latest version of gamescope-session improves logging and log management by piping all session output to the system logs accessible with `journalctl` and no longer using several different log files in the user's home directory.
> update to latest upstream version

- playtron-os-files/playtron-os-files.spec
to the latest upstream release. Add the new zram configuration and remove the old swap configuration.
> [playtron-os-files] Update version

- playtron-os-files/playtron-os-files.spec
to include 'rsync' for the factory reset script.
> update playtron-os-files dependencies

- udev-media-automount/udev-media-automount.spec
> update udev-media-automount to 0.1.0+71

- .github/workflows/python3-edl-upload.yml
- .github/workflows/valve-firmware-upload.yml
This is causing a failure when uploading the source RPMs.
> Remove old Copr chroot excludes

- gamescope-session/gamescope-session.spec
We need the latest feature of the session which allows us to apply environment variables globally.
> update to latest commit of gamescope session
